name: Tagging

on:
  push:
    branches: ["dev"]

jobs:
  tagging:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: TriPSs/conventional-changelog-action@v3
        name: Tagging and Changelog
        with:
          git-user-nane: "Antonio Donis"
          git-user-email: "antoniojosedonishung@gmail.com"
          git-message: "chore(release): {version}"
          version-file: "version.json"
