name: Test

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11.0-2

      # Assemble the jar file without running tests
      - name: Clean and build
        run: sbt "set assembly / test := {}" clean assembly

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11.0-2

      - name: Lint
        run: scalafmt --check src/
  test:
    runs-on: ubuntu-22.04
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11.0-2

      - name: Setup docker environment
        run: docker-compose up -d

      - name: Clean and test
        run: sbt clean test

      - name: Clean docker environment
        run: docker-compose down --rmi all -v --remove-orphans