name: Test

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11.0-2

      # Assemble the jar file without running tests
      - name: Clean and build
        run: sbt "set assembly / test := {}" clean assembly

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11.0-2

      - name: Setup docker environment
        run: docker-compose -f docker-compose.testing.yaml up -d

      - name: Clean and test
        run: sbt -DDATABASE_HOST=${{ vars.DATABASE_HOST }} -DDATABASE_PORT=${{ vars.DATABASE_PORT }} -DDATABASE_NAME=${{ vars.DATABASE_NAME }} -DDATABASE_USER=${{ vars.DATABASE_USER }} -DDATABASE_PASSWORD=${{ vars.DATABASE_PASSWORD }} clean test

      - name: Clean docker environment
        run: docker-compose -f docker-compose.testing.yaml down --rmi all -v --remove-orphans